#!/bin/bash
#!/bin/bash

gentkid=$1

if [[ "$gentkid" == "" ]] ; then
  echo "provide gentk ID"
  exit -1
fi

ipfsgw='https://gateway.fxhash.xyz/ipfs/'

curl --request POST \
    --header 'content-type: application/json' \
    --url 'https://api.fxhash.xyz/graphql' \
    -s \
    --data '{"query":"query ($generativeTokenId: Float) { generativeToken(id: $generativeTokenId) { id slug name originalSupply supply pricingFixed { price opensAt } pricingDutchAuction { levels restingPrice decrementDuration opensAt finalPrice } author {id name} actions { id type createdAt } metadataUri reserves { amount data } id } }","variables":{"generativeTokenId":'$gentkid'}}'


