#!/bin/bash

gentkid=$1
st=$2

if [[ "$gentkid" == "" ]] ; then
  echo "provide gentk ID"
  exit -1
fi

if [[ "$st" == "" ]] ; then
  st=-1
fi

if [[ "$st" != "-1" ]] ; then

curl --request POST \
    --header 'content-type: application/json' \
    --url 'https://api.fxhash.xyz/graphql' \
    -s \
    --data '{"query":"query ($ids: [Float!]!, $take: Int, $skip: Int, $filters: ActionFilter) { generativeTokensByIds(ids: $ids) { id slug name originalSupply supply price author { id name } actions(take:$take, skip: $skip, filters: $filters) { id type createdAt issuer { id }  metadata  } metadataUri } } ","variables":{"ids":['$gentkid'],"take":50,"skip":'$st',"filters":{"type_in":["MINTED_FROM"]}}}'

else

  st=0

  while [[ true ]] ; do
    curl --request POST \
        --header 'content-type: application/json' \
        --url 'https://api.fxhash.xyz/graphql' \
        -s \
        --data '{"query":"query ($ids: [Float!]!, $take: Int, $skip: Int, $filters: ActionFilter) { generativeTokensByIds(ids: $ids) { id slug name originalSupply supply price author { id name } actions(take:$take, skip: $skip, filters: $filters) { id type createdAt issuer { id }  metadata  } metadataUri } } ","variables":{"ids":['$gentkid'],"take":50,"skip":'$st',"filters":{"type_in":["MINTED_FROM"]}}}'

    n=`curl --request POST \
        --header 'content-type: application/json' \
        --url 'https://api.fxhash.xyz/graphql' \
        -s \
        --data '{"query":"query ($ids: [Float!]!, $take: Int, $skip: Int, $filters: ActionFilter) { generativeTokensByIds(ids: $ids) { id slug name originalSupply supply price author { id name } actions(take:$take, skip: $skip, filters: $filters) { id type createdAt issuer { id }  metadata  } metadataUri } } ","variables":{"ids":['$gentkid'],"take":50,"skip":'$st',"filters":{"type_in":["MINTED_FROM"]}}}' | jq '.data.generativeTokensByIds[].actions | length' `

    if [[ "$n" != "50" ]] ; then break ; fi
    st=`echo "$st + 50" | bc`

  done

fi
