#!/bin/bash

st=0

if [[ "$1" != "" ]] ; then
  st=$1
fi

curl -s --request POST \
    --header 'content-type: application/json' \
    --url 'https://api.fxhash.xyz/graphql' \
    --data '{"query":"query Users($take: Int, $skip: Int) {\n  users(take: $take, skip: $skip) {\n    id name createdAt\n    generativeTokens {\n      id slug name author { id name }\n    }\n    \n  }\n}","variables":{"skip":'$st',"take":50}}'

