#!/bin/bash
#
# To the extent possible under law, the person who associated CC0 with
# the author has waived all copyright and related or neighboring rights
# to the author.
#
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

# fxhash v1.0
#

gentkid=$1

if [[ "$gentkid" == "" ]] ; then
  echo "provide gentk ID"
  exit -1
fi

curl --request POST \
  --header 'content-type: application/json' \
  --url 'https://api.fxhash.xyz/graphql' \
  -s \
  --data '{"query":"query ExampleQuery($generativeTokenId: Float) {\n\n  generativeToken(id: $generativeTokenId) {\n    id\n    slug\n    name\n    metadata\n    thumbnailUri\n    displayUri\n    royalties\n    createdAt\n    mintOpensAt\n    pricingFixed {\n      price\n      opensAt\n    }\n    pricingDutchAuction {\n      levels\n      restingPrice\n      decrementDuration\n      opensAt\n      finalPrice\n    }\n    author {\n      id\n      name\n    }\n    splitsPrimary {\n      pct\n      user {\n        id\n        name\n      }\n    }\n    splitsSecondary {\n      pct\n      user {\n        id\n        name\n      }\n    }\n    features\n    moderationReason\n    flag\n    originalSupply\n    supply\n    balance\n    tags\n    labels\n    reserves {\n      data\n      amount\n      method\n    }\n }\n}","variables":{"generativeTokenId":'$gentkid'}}'

