#!/bin/bash
#
# To the extent possible under law, the person who associated CC0 with
# the author has waived all copyright and related or neighboring rights
# to the author.
#
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

# fxhash v1.0
#

# if 'st' is specified, will only take the 50 (max) next after start
# otherwise will iterate through all actions
#
# resulting dataset can be parsed as follows:
#
#  ...  | jq -c '.data[].actions[]' ...
#

gentkid=$1
st=$2

if [[ "$gentkid" == "" ]] ; then
  echo "provide gentk ID"
  exit -1
fi

if [[ "$st" == "" ]] ; then
  st=-1
fi

if [[ "$st" != "-1" ]] ; then

  curl --request POST \
    --header 'content-type: application/json' \
    --url 'https://api.fxhash.xyz/graphql' \
    -s  \
    --data '{"query":"query ExampleQuery($generativeTokenId: Float, $skip: Int, $take: Int) {\n\n  generativeToken(id: $generativeTokenId) {\n    id\n    slug\n    actions(skip: $skip, take: $take) {\n      id\n      type\n      metadata\n      numericValue\n      createdAt\n      opHash\n      issuer {\n        id\n        name\n      }\n      target {\n        id\n        name\n      }\n      token {\n        id\n        slug\n      }\n      objkt {\n        id\n        slug\n      }\n    }\n  }\n}","variables":{"generativeTokenId":'$gentkid',"skip":'$st',"take":50}}'

else

  st=0

  while [[ true ]] ; do

    curl --request POST \
      --header 'content-type: application/json' \
      --url 'https://api.fxhash.xyz/graphql' \
      -s \
      --data '{"query":"query ExampleQuery($generativeTokenId: Float, $skip: Int, $take: Int) {\n\n  generativeToken(id: $generativeTokenId) {\n    id\n    slug\n    actions(skip: $skip, take: $take) {\n      id\n      type\n      metadata\n      numericValue\n      createdAt\n      opHash\n      issuer {\n        id\n        name\n      }\n      target {\n        id\n        name\n      }\n      token {\n        id\n        slug\n      }\n      objkt {\n        id\n        slug\n      }\n    }\n  }\n}","variables":{"generativeTokenId":'$gentkid',"skip":'$st',"take":50}}'

    n=`curl --request POST \
      --header 'content-type: application/json' \
      --url 'https://api.fxhash.xyz/graphql' \
      -s \
      --data '{"query":"query ExampleQuery($generativeTokenId: Float, $skip: Int, $take: Int) {\n\n  generativeToken(id: $generativeTokenId) {\n    id\n    slug\n    actions(skip: $skip, take: $take) {\n      id\n      type\n      metadata\n      numericValue\n      createdAt\n      opHash\n      issuer {\n        id\n        name\n      }\n      target {\n        id\n        name\n      }\n      token {\n        id\n        slug\n      }\n      objkt {\n        id\n        slug\n      }\n    }\n  }\n}","variables":{"generativeTokenId":'$gentkid',"skip":'$st',"take":50}}' | jq '.data.generativeToken.actions | length' `

    if [[ "$n" != "50" ]] ; then break ; fi
    st=`echo "$st + 50" | bc`

  done

fi


